Repository dibk100/2024-Code-Study-Group, pull requests merged in 2024-09, with the labels that each got.

#166 [dibk] chapter15 이진탐색
  PreviousQuestions/dibk_Q27_find.py
  PreviousQuestions/dibk_Q28_fixed_point.py
  PreviousQuestions/dibk_Q29_install the router.py
  PreviousQuestions/dibk_Q30_search.py
Labels: BinarySearch

#165 [Mijeong] ch15(이진탐색 심화) question27-30
  PreviousQuestions/cmj_q27_certain_number_count_in_sorted_array.py
  PreviousQuestions/cmj_q28_find_fixed_point.py
  PreviousQuestions/cmj_q29_modem_install.py
  PreviousQuestions/cmj_q30_lyrics_search.py
Labels: BinarySearch

#169 [dibk] ch14_sorting Q23~26
  PreviousQuestions/dibk_Q23_koenmath.py
  PreviousQuestions/dibk_Q24_antenna.py
  PreviousQuestions/dibk_Q25failure_late.py
  PreviousQuestions/dibk_Q26_cards.py
Labels: sorting

#168 [Mijeong] ch14 question23-26
  PreviousQuestions/cmj_q23_scores.py
  PreviousQuestions/cmj_q24_antenna.py
  PreviousQuestions/cmj_q25_fail_rate.py
  PreviousQuestions/cmj_q26_card_sort.py
Labels: sorting

#172 [dibk] ch13 DFS/BFS
  PreviousQuestions/dibk_Q15_find_city.py
  PreviousQuestions/dibk_Q16_laboratory.py
  PreviousQuestions/dibk_Q17_competitive-contagion.py
  PreviousQuestions/dibk_Q18_conversion.py
Labels: DFS/BFS

#171 [Mijeong] ch13 question 15-18
  PreviousQuestions/cmj_q15_find_city_within_distance.py
  PreviousQuestions/cmj_q16_lab.py
  PreviousQuestions/cmj_q17_competitive_infection.py
  PreviousQuestions/cmj_q18_parenthesis_transform.py
Labels: DFS/BFS

#175 [dibk] ch13 Q19~Q21
  PreviousQuestions/dibk_Q19_insert-operator.py
  PreviousQuestions/dibk_Q20_avoid surveilance.py
  PreviousQuestions/dibk_Q21_population-movement.py
Labels: DFS/BFS

#174 [Mijeong] ch13 question19-22
  PreviousQuestions/cmj_q19_operator_insertion.py
  PreviousQuestions/cmj_q20_avoid_observation.py
  PreviousQuestions/cmj_q21_population_move.py
  PreviousQuestions/cmj_q22_block_move.py
Labels: DFS/BFS

#177 [Mijeong] ch12 question7-10
  PreviousQuestions/cmj_q07_lucky_straight.py
  PreviousQuestions/cmj_q08_string_rearrange.py
  PreviousQuestions/cmj_q09_string_compression.py
  PreviousQuestions/cmj_q10_lock_and_key.py
Labels: implementation

#178 [dibk] ch12 Q7toQ10
  PreviousQuestions/dibk_Q07_lucky-straight.py
  PreviousQuestions/dibk_Q08_str-sorting.py
  PreviousQuestions/dibk_Q09_str-compression.py
  PreviousQuestions/dibk_Q10_lock-and-key.py
Labels: implementation
